### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Coopeh** [peacetara/slab#6]
Hi,

I've followed your readme, but unfortunately I'm receiiving the following error:

Traceback (most recent call last):
  File "/usr/local/bin/slab", line 11, in <module>
    load_entry_point('slab==0.1.1', 'console_scripts', 'slab')()
  File "/usr/local/lib/python3.6/site-packages/slab-0.1.1-py3.6.egg/slab/main.py", line 119, in main
  File "/usr/local/lib/python3.6/site-packages/slab-0.1.1-py3.6.egg/slab/slablib.py", line 96, in unlock
  File "/usr/local/lib/python3.6/site-packages/slab-0.1.1-py3.6.egg/slab/slablib.py", line 51, in _loadKeys
TypeError: 'NoneType' object is not subscriptable

I used the keychain method to store the password, and I'm using MacOS 10.13.1. Let me know if you need any more details.

Cheers,
Ed

**Comment by peacetara** [comment]
Hi Ed,

This likely means your master password is wrong, or unknown.  How are you telling slab about your master password? I'd recommend using the keychain option.

**Comment by Coopeh** [comment]
Hi peacetara,

I thought it may have been that, but the password is definitely correct. I'm using keychain currently. I am using a 1Password online account if that makes any difference? I assume the sqlite db will still be correct.

**Comment by peacetara** [comment]
This code is meant for local vaults, not the 1password online remote vaults.

If you are using the 1password online account, it probably won't work(it's untested and your experience leads me to believe it won't work). 

You should use the op tool: https://support.1password.com/command-line-getting-started/
, and there is a tool like slab for the op tool here: https://github.com/tomvachon/dpaf

Sorry, but I have little interest in the remote vault, even if the 1P people seem to think it's the one-true-way.  You are welcome to marry the DPAF stuff with slab if you want as a pull request to support both options, I'm not against that at all.

**Comment by peacetara** [comment]
As an aside, if I remember correctly, the online DB still uses the sqlite file, but it's a diff. profile name.

@Coopeh if you want to see if it's possible to use slab, run this against your sqlite3 file:

`select id, profile_name from profiles;`

to see what the profilename is supposed to be, and then you can modify 

`k.unlock(password, filter='sudolikeaboss')`

that line in main.py to be:

`k.unlock(password, filter='sudolikeaboss', profileName='YOURPROFILENAME')`

This should work.  if it's just a profile change.  Otherwise I'm not sure how the online vault is stored locally in the sqlite3 file, you would have to either make a test sqlite3 file like I did and send it to me and wait for me to be very bored, or figure it out and update the code appropriately.

the op and dpaf tool is probably easier tho, but will require an online Internet connection.

**Comment by Coopeh** [comment]
There doesn't seem to be anything in the profiles table. I'll give dpaf a go, thanks!
