### ISSUE TITLE
Empty dropdown with Dropbox synced secrets.

### ISSUE THREAD

**Issue by soerenkampschroer** [peacetara/slab#8]
I installed slab after getting tired of constantly copy/pasting my passwords. Install worked fine but I'm having trouble getting my passwords to show up. I can invoke slab and the window appears but the dropdown list is empty. I don't get any errors as far as I can tell but I don't know enough about python to be sure. I added my master password to my Keychain and also tried the file approach.

My login items have "sudolikeaboss://local" set as website, is that enough to identify them as slab entries?

Thanks for making this tool!

Python 3.6.4
1Password 6.8.5
macOS 10.11.6

**Comment by peacetara** [comment]
If you look at the source: https://github.com/peacetara/slab/blob/master/src/python/slab/slablib.py#L88 They need to be the exact string, without any double quotes, spaces, etc.

Attached is a screenshot of what the website field should look like for an entry in the 1password GUI.
 
<img width="262" alt="sudolikeaboss" src="https://user-images.githubusercontent.com/103946/34912291-6796d2d8-f892-11e7-9036-441d980c568b.png">

Also of course, they have to be in your *LOCAL* vault, doing them in a remote vault won't work.

**Comment by soerenkampschroer** [comment]
I'm syncing my vault with Dropbox, is that considered to be a remote vault? I made sure that the file at "~/Library/Application\ Support/1Password\ 4/Data/OnePassword.sqlite" is there.

The exact website on my login items is "sudolikeaboss://local" (without the quotes of course).

**Comment by soerenkampschroer** [comment]
Hey @peacetara,

Just to let you know, I tried reinstalling and I can't get it to work. No errors as far as I can see here either. Just an empty dropdown list.

Cheers!

**Comment by peacetara** [comment]
I'm guessing the Dropbox sync vault(s) are in a diff. format and are not a part of the SQLite file.  AgileBits is very un-helpful about their actual disk formats and usage(s) .. i.e. where they use the diff. formats and why.

I'm guessing this code won't work well for you, since the actual secrets do not appear to be in the SQLite file.  You could try putting the sudolikeaboss secrets in a local only vault, which means they should then be in the SQLite file, and slab should then see them. 

 Otherwise I'm not sure what to suggest.  I don't really have the time and energy right now to track down the Drobox synced secrets, their particular format and integrate it all into slab, but I would welcome you to do this work and merge it back into slab.
